= Message Driven
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::partial$include.adoc[]


[quote,'Jonas Bonér, Dave Farley, Roland Kuhn, and Martin Thompson, et al.', 'link:{reactive-manifesto}[Reactive Manifesto]' ]
Reactive Systems rely on link:{glossary-asynchronous}[asynchronous] link:{glossary-message-driven}[message-passing] to establish a boundary between components that ensures loose coupling, isolation and link:{glossary-location-transparency}[location transparency]. This boundary also provides the means to delegate link:{glossary-failure}[failures] as messages. Employing explicit message-passing enables load management, elasticity, and flow control by shaping and monitoring the message queues in the system and applying link:{glossary-back-pressure}[back-pressure] when necessary. Location transparent messaging as a means of communication makes it possible for the management of failure to work with the same constructs and semantics across a cluster or within a single host. link:{glossary-non-blocking}[Non-blocking] communication allows recipients to only consume link:{glossary-resource}[resources] while active, leading to less system overhead.


A Message is some data sent to a specific address. In Message Driven systems, each component has a unique address other components can send messages to. Each of these components, or recipients, awaits messages and reacts to them.

In traditional programming models the _Component A_ invoking a method in _Component B_ was coupled in time. When passing messages, _Component A_ and _Component B_ are decoupled in time. This decoupling allows _Component A_ to send a message to _Component B_ and not wait for _Component B_ to complete the handling of that message. Components on a message driven system often have a queue where incoming messages can be stored in case of a load spike.

In Message Driven systems, each component send items to a fixed recipient. In xref:event-driven.adoc[Event Driven] systems, on the other hand, each component produces items of data with a fixed sender and shared them with any consumer. This comparison, though, is misleading: the term 'Message Driven' refers to a building block on a system and 'Event Driven' refers to a higher level property of a system. So, using Message Driven tools we can build an Event Driven system.