site:
  title: "Akka Platform Guide"
  url: https://developer.lightbend.com/docs/akka-platform-guide
  
content:
  sources:
  - url: git@github.com:akka/akka-platform-guide.git
    start-paths:
    - docs-source/docs
    branches: [main]

ui: 
  bundle:
    url: https://github.com/lightbend/antora-ui-lightbend-theme/raw/master/build/ui-bundle.zip
    snapshot: true
    
runtime:
  fetch: true

asciidoc:

  attributes:
    # the following two attributes cause review and todo notes to display
    # review: ''
    # todo: ''
    doc-title: 'Akka Platform Guide'
    # the following turns on next and previous links in the new template
    page-pagination: ""

output:
  dir: ./../target
  clean: true
