apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "shopping"
---
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: shopping-cart-service
  namespace: "shopping"
spec:
  image: docker.io/<your username>/shopping-cart-service:<tag>
  jdbc:
    credentialsSecret: shopping-cart-service-jdbc-secret
  cloudKafkaConfluent:
    credentialsSecret: shopping-cart-service-kafka-secret
