= What makes up a service?
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]


ifdef::todo[(Lagom Service Descriptors https://www.lagomframework.com/documentation/1.6.x/java/ServiceDescriptors.html)]


A service is made up by its API (request and response types, strict vs stream, synchronous vs asynchronous), and discovery information (URL, topic name).

To communicate the API consistently, we recommend using schema-first approaches. The schemas are to be shared by the service implementation and its clients. From the schema the implementing code is generated and used to implement the service and the client code.

== Synchronous Services

This guide illustrates building service APIs for synchronous communication for use cases which require an instant reply. Most often synchronous communication issues a single request and expects a single reply. Other cases open communication channels for continued communication with possibly ongoing replies.

Synchronous communication gives results and errors immediately so the client can react before continuing its processing, but that often means the client doesn't progress until it received the response.

=== gRPC

gRPC services use Protobuf as their language-agnostic schema and which translate to efficient serialisation.
Protobuf can even be used as a serialization format for messages on Kafka topics. So that both producer and consumer agree on the format.

Akka gRPC adds the appropriate plug-ins to the build system of the application to generate Java or Scala classes corresponding to the Protobuf schema.

xref:grpc-services.adoc[gRPC services] explains how to use gRPC for service APIs.

=== HTTP with JSON / RESTful

The ubiquitous communication protocol is HTTP with text-based messages in JSON. Even though JSON lacks a commonly used schema description, its simplicity, human-readability and support in Javascript has made the de-facto standard for synchronous communication over system boundaries.

xref:rest-services.adoc[REST services] explains how to create RESTful APIs with Akka HTTP.

== Asynchronous Services

Asynchronous service communication decouples services at a higher degree. Sending and receiving is decoupled in time and both parts do not necessarily act at the same time.
To ensure delivery of messages asynchronous communication may require extra measures like sending acknowledgements.

* Kafka
* Show protobuf (implemented in Cloudflow, examples in Alpakka Kafka)
* Confluent Cloud Protobuf https://www.confluent.io/blog/using-protobuf-in-confluent-cloud/
* Broker discovery https://doc.akka.io/docs/alpakka-kafka/current/discovery.html

== Service Discovery

ifdef::todo[Transport information coordinates (URL, HTTP method, broker & topic), serialization]

ifdef::todo[Service descriptor agnostic to transport?]

ifdef::todo[Service discovery, Deployed services are announced as DNS SRV records by Kubernetes.]

== Protecting our Service

Circuit breakers

== Structuring our Service

ifdef::todo[Anti-corruption layer]
