name: Link Validator

on:
  # TODO remove `on push` and `on pull_request_target`
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  schedule:
    - cron:  '0 6 * * *'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Antora
        run: make all

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Install Coursier comman line tool
        run: curl -fLo cs https://git.io/coursier-cli-linux && chmod +x cs && ./cs

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.1.11 -- scripts/validator.conf
